[package]
name = "verifier-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = { version = "1.30", features = ["float"] }
# Direct dep pins the force-cross feature so gmp-mpfr-sys builds on musl target
gmp-mpfr-sys = { version = "1.7", features = ["force-cross"] }

[profile.release]
opt-level = 3
lto = true
